spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:mysql://${DATA_HOSTNAME:localhost}:3333/ecommerce_orders_db?&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATA_USERNAME:davidking}
    password: ${DATA_PASSWORD:davidking!!}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  port: 8004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
  instance:
    statusPageUrl: https://${eureka.hostname}/info
    healthCheckUrl: https://${eureka.hostname}/health
    homePageUrl: https://${eureka.hostname}/
    appname: orders-service

commerce:
  registry:
    user: eurekausr
    passwd: eurekapasswd
  clients:
    accounts:
      serviceName: accounts-service
      baseUrl: http://localhost:8000
      findByAccountIdRefUrl: /accounts/{id}/reference